version: "3.8"

services:
  frcm_app:
    build: /FRCM-app
    ports:
      - 8000:8000
    volumes:
      - /FRCM-app:/backend
    image: frcm_app:django-backend
    container_name: backend
    command: ["/root/.local/bin/poetry", "run", "python", "manage.py", "runserver", "8000"]

  frontend-app:
    build: /frontend
    ports:
      - 3000:3000
    volumes:
      - /frontend:/app
    image: frontend-app:react-frontend
    container_name: frontend
    command: ["npm", "start"]