version: '3.7'

services:
  bl_app:
    build: /bl-app
    ports:
      - "8000:8000"
    volumes:
      - /bl-app:/app

  dhp_app:
    build: /dhp-app
    ports:
      - "8001:8000"
    volumes:
      - /dhp-app:/app

  frcm_app:
    build: /frcm-app
    ports:
      - "8002:8000"
    volumes:
      - /frcm-app:/app

  frontend-app:
    build: /frontend-app
    ports:
      - "8003:8000"
    volumes:
      - /frontend-app:/app
