# Generated by Django 5.0.3 on 2024-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcmApp', '0003_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
