# Generated by Django 5.0.3 on 2024-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frcmApp', '0004_weatherdata_latitude_weatherdata_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireRiskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
