# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Echo npm config and file paths
        run: |
          npm config get prefix
          ls -l $(npm config get prefix)/lib
          echo "Home directory: $HOME"
          echo "Working directory: $PWD"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
        working-directory: ./frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

        # Tester er ikke implementert skikkelig enda - Placeholder
      # - name: Run tests
      #   run: npm test

      - name: Build
        run: npm run build
        working-directory: ./frontend
